# Label any pull request that includes changes to Terraform files.
root:
- changed-files:
  - any-glob-to-any-file: ['*.tf']

# Label any pull request that includes changes to Markdown documentation files.
documentation:
- changed-files:
  - any-glob-to-any-file: ['*.md']
