name: Release with SemVer

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semantic versioning
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        
      - name: Create Release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: releaseNotes } = await github.rest.repos.generateReleaseNotes({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${process.env.NEXT_VERSION}`,
              previous_tag_name: process.env.PREVIOUS_TAG
            });
            
            const { data: release } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${process.env.NEXT_VERSION}`,
              name: `v${process.env.NEXT_VERSION}`,
              body: releaseNotes.body,
              draft: false,
              prerelease: false
            });
            
            return release.id;
        env:
          NEXT_VERSION: ${{ steps.semver.outputs.version }}
          PREVIOUS_TAG: ${{ steps.semver.outputs.previous_tag }}
