# .github/workflows/labeler.yml
name: Labeler
on:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run labeler
        uses: actions/labeler@v3
        env:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
